import type { Metadata } from "next";
import "./globals.css";
import { Cabin } from "next/font/google";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Luanda Office Center",
  description: "Generated by create next app",
};

const fontConfig = Cabin({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <body className={fontConfig.className}>{children}</body>
    </html>
  );
}
