import type { Metadata } from "next";
import "./globals.css";
import { Cabin } from "next/font/google"


export const metadata: Metadata = {
  title: "Luanda Office Center",
  description: "Generated by create next app",
};

const fontConfig = Cabin({
  subsets: ["latin"]

})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fontConfig.className}
      >
        {children}
      </body>
    </html>
  );
}
